export const lightTheme = {
    body: '#f4f8fb;',
    text: '#363537',
    greytowhite: '#c9ccd0',
    toggleBorder: '#FFF',
    background: '#363537',
    aside: '#fff',
    menu: '#a2acb8',
    shadow: '1px 0px 0px 0px #f6f6f7',
    image: './images/moon.png',
    headersvg: '#000',
    time: '#a2acb8',
}
export const darkTheme = {
    body: '#616161',
    text: '#FAFAFA',
    greytowhite: '#fff',
    toggleBorder: '#6B8096',
    background: '#999',
    aside: '#adadad',
    menu: '#fff',
    shadow: '1px 0px 0px 0px #d0d0d0',
    image: './images/sun.png',
    headersvg: '#fff',
    time: '#fff',
}